version: '3.9'

services:
#  scms-sbsuite-db:
#    image: mysql:8.0
#    restart: unless-stopped
#    environment:
#      - MYSQL_ROOT_PASSWORD=pswd
#    ports:
#      - '3306:3306'
#    volumes:
#      - ./mysql:/var/lib/mysql
#      - ./database/initdb/:/docker-entrypoint-initdb.d/

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - eureka-server
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://bitbucket.org/JavaPantry/config-server-repo
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=JavaPantry
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=C98LcSyS9wbmFuevstdz
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=master
      - SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START=true
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=/{application}

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    depends_on:
      - config-server

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    image: inventory-service:latest
    container_name: inventory-service
    restart: unless-stopped
    depends_on:
      - api-gateway

  store-service:
    build:
      context: ./store-service
      dockerfile: Dockerfile
    image: store-service:latest
    container_name: store-service
    restart: unless-stopped
    depends_on:
      - api-gateway

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    container_name: product-service
    restart: unless-stopped
    depends_on:
      - api-gateway

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: order-service:latest
    container_name: order-service
    restart: unless-stopped
    depends_on:
      - api-gateway

  sbsuite-quart:
    build:
      context: ./springcloud-sbsuite-quart
      dockerfile: Dockerfile
    image: sbsuite-quart:latest
    container_name: sbsuite-quart
    restart: unless-stopped
    depends_on:
      - api-gateway

#volumes:
#  prfdb:
