### get eclient default profiles
GET {{config-host}}/eclient/default

### get eclient local profiles
GET {{config-host}}/eclient/local

### get eclient2 default profiles
GET {{config-host}}/eclient2/default

### get eclient2 local profiles
GET {{config-host}}/eclient2/local

### get data-aggregation-service default profiles
GET {{config-host}}/data-aggregation-service/default

### get data-aggregation-service local profiles
GET {{config-host}}/data-aggregation-service/local


### Encrypt the data (send raw data)
POST {{config-host}}/encrypt

eclient-app-local-secured

### Decript the data (send raw data)
POST {{config-host}}/decrypt

11f093e57adcf38c91ef3af5762bea3edc8b4acf313e37d651266d440e5342a7fe3dfa5cd958fb7fc0bca1d1d07a8740

### get local-secure profiles
GET {{config-host}}/eclient/local-secure

