### get eclient via gateway via gateway- OK
GET {{gateway-host}}/main/test

### get direct inventory-service - OK
GET {{gateway-host}}/inventory-service/main/test

### get config-var from inventory-service - OK
GET {{gateway-host}}/inventory-service/main/config-var

### get eclient2 from inventory-service - OK
GET {{gateway-host}}/inventory-service/main/eclient2/name

### get store-service via gateway - OK
GET {{gateway-host}}/new/name

### get direct eclient2 - OK
GET {{gateway-host}}/store-service/new/name

