### get inventory-service via gateway
GET {{gateway-host}}/inventory/test

### get direct inventory-service /inventory/test
GET {{gateway-host}}/inventory-service/inventory/test

### get direct store-service via gateway
GET {{gateway-host}}/inventory/

### get direct store-service via inventory-service
GET {{gateway-host}}/inventory-service/inventory/

### get config-var from inventory-service - OK
GET {{gateway-host}}/inventory-service/inventory/config-var

### get store-service via gateway - OK
GET {{gateway-host}}/store/inventory

### get direct store-service - OK
GET {{gateway-host}}/store-service/store/inventory

### get direct product-service
GET {{gateway-host}}/product-service/product/

### get direct order-service
GET {{gateway-host}}/order-service/order/

### get config-var from product-service
#GET {{gateway-host}}/product-service/product/config-var
